### ISSUE TITLE
Fetch tables metadata takes too long

### ISSUE THREAD

**Issue by martingehrke** [datanymizer/datanymizer#145]
`Fetch tables metadata...`
takes more time than a full database dump.

I have filters in place for only 4 tables I need out of 100+ but this still takes longer than I expect.

**Comment by martingehrke** [comment]
I see `SELECT pg_catalog.pg_get_serial_sequence ( ? )` millions of times on the db

**Comment by angryjohnnie** [comment]
> `Fetch tables metadata...` takes more time than a full database dump.

I came here today to say exactly this. I have 20-something schemas. Each with about 50 tables. The metadata fetch takes over an hour. the actual db dumping part takes probably 10 min to a local disk.

TY for the tool, it does the thing, I just wish it were quicker.

**Comment by evgeniy-r** [comment]
Hello! I think that it is some kind of bug, we will check this.

**Comment by martingehrke** [comment]
Let me know how I can help

**Comment by evgeniy-r** [comment]
I have some ideas, could you please provide the database schema (the dump without data)?

**Comment by martingehrke** [comment]
angryjohnnie <https://github.com/angryjohnnie>, are you able to easily?
this is a production database, I can't just share our schema, sorry.

**Comment by angryjohnnie** [comment]
> angryjohnnie <https://github.com/angryjohnnie>, are you able to easily? this is a production database, I can't just share our schema, sorry.
> […](#)

im not sure what our policy is regarding sharing that schema. I can see if I can find out though.

**Comment by angryjohnnie** [comment]
It looks like I am not allowed to share our schema either, unfortunately.

**Comment by evgeniy-r** [comment]
OK, then we will try to fix this without these schemas.

**Comment by martingehrke** [comment]
if you have branch or changes you would like to test, I can run it and
supply logs

**Comment by marmik18** [comment]
I have a similar kind of issue, I have 4 schemas and around 20 tables in each of the schema. I also tried passing filter args using the [cli <PG_DUMP_ARGS>](https://github.com/datanymizer/datanymizer/blob/main/docs/pg_datanymizer.md#args). But it still takes more than 20 mins to fetch the metadata.

**Comment by evgeniy-r** [comment]
Can anybody run dumping with the [tracing](https://github.com/datanymizer/datanymizer/pull/153) branch and copy the output here? I can build a binary if required.

**Comment by martingehrke** [comment]
I can if you can build a binary.

**Comment by evgeniy-r** [comment]
Platform? (win/linux/mac - Darwin or ARM)

**Comment by martingehrke** [comment]
sorry, linux amd64

**Comment by evgeniy-r** [comment]
[pg_datanymizer.zip](https://github.com/datanymizer/datanymizer/files/8072135/pg_datanymizer.zip)

**Comment by martingehrke** [comment]
pg_datanymizer_debug_build --config ../config.yaml [...]
Inspecting tables ...
Inspecting completed in 4 seconds
Inspecting table dependencies...

and it has been stuck at the stage for hour+

**Comment by evgeniy-r** [comment]
Thank you very much, I will look into it...

**Comment by evgeniy-r** [comment]
Try the updated version, please.
[pg_datanymizer.zip](https://github.com/datanymizer/datanymizer/files/8082457/pg_datanymizer.zip)

**Comment by martingehrke** [comment]
this one worked!

$ time ../bin/pg_datanymizer_new_debug --config ../config.yaml [...]
Fetching tables metadata...
Inspecting tables ...
Inspecting completed in 59 seconds
Inspecting table dependencies...
Inspecting completed in 0 seconds
Processing table dependencies...
Processing completed in 0 seconds
Fetching completed in 59 seconds
Sorting tables...
Sorting completed in 0 seconds
Prepare data scheme...
[1 / 373] Prepare to dump table: public.cities

**Comment by evgeniy-r** [comment]
@martingehrke, can you check this one too please?
[pg_datanymizer.zip](https://github.com/datanymizer/datanymizer/files/8104212/pg_datanymizer.zip)

**Comment by martingehrke** [comment]
sorry for the late reply. this one works as well;

Fetching tables metadata...
Inspecting tables ...
Inspecting completed in 1 minute
Inspecting table dependencies...
Inspecting completed in 0 seconds
Processing table dependencies...
Processing completed in 0 seconds
Fetching completed in 1 minute
Sorting tables...
Sorting completed in 0 seconds
Prepare data scheme...
