### ISSUE TITLE
Print message if there's newer version of datanymizer

### ISSUE THREAD

**Issue by mgrachev** [datanymizer/datanymizer#157]
Hi 👋

What do you think about adding the [`update-informer`] crate to the project to print a message if there is a newer version of datanymizer?

`update-informer` has support of GitHub releases.

[`update-informer`]: https://github.com/mgrachev/update-informer

**Comment by evgeniy-r** [comment]
Hi, this is interesting, but can we don't create any files during the checking?

**Comment by mgrachev** [comment]
Now there is no such possibility.
`update-informer` only creates a file in a cache directory to not spam API of registries.
How would like to use this crate?

**Comment by evgeniy-r** [comment]
Just run it on some CLI flag (I don't like automatic check on start).

E.g.:
```sh
pg_datanymizer --check-updates
---  There is no updates  ---
```

**Comment by mgrachev** [comment]
I've just added the ability to no create cache files.
https://github.com/mgrachev/update-informer#cache-file

**Comment by evgeniy-r** [comment]
Can you prepare a PR?

**Comment by mgrachev** [comment]
> Can you prepare a PR?

Sure 👌
