### ISSUE TITLE
When ever I try to run with ssl on its errors out with: no matches found: url?sslmode=verify-full

### ISSUE THREAD

**Issue by dineshkarn1** [datanymizer/datanymizer#167]

**Comment by akirill0v** [comment]
@dineshkarn1 Hello! Can you specify a full CLI command to run?

**Comment by evgeniy-r** [comment]
Hello!

The library `tokio-postgres` (which is used in Datanymizer) does not support such SSL mode for now:
https://github.com/sfackler/rust-postgres/blob/8785773e8e332f665471d79258dcc8f0051ebf27/tokio-postgres/src/config.rs#L407

You can use only `disable`, `prefer` and `require` values. Also you could set `accept_invalid_hostnames` and `accept_invalid_certs` flags if required.

**Comment by dineshkarn1** [comment]
It worked now thanks
