### ISSUE TITLE
when tera template fails, datanymizer should show descriptive error to stderr

### ISSUE THREAD

**Issue by krysopath** [datanymizer/datanymizer#182]
```
Error: Failed transform Failed to render 'TemplateTransformerTemplate'
```

Does not exactly specify what, how and were. Was it `Err()` from a tera function/filter, or from function added by datanymizer. What were those arguments. Or was it just a templating error due to not observing template syntax? According to [tera errors](https://github.com/Keats/tera/blob/master/src/errors.rs) we have several classes. Maybe we can let them bubble up.

I believe this would tremendously improve working with the complexity of templating in datanymizer <3

**Comment by akirill0v** [comment]
Hi guys! Yep, I'll do it soon... I need to test some features and fixes for previous changes.

**Comment by akirill0v** [comment]
@krysopath I have a good news ;) We've added verbose logging to explain errors. https://github.com/datanymizer/datanymizer/pull/184
Now you can use `-v`, `-vv`, `-vvv` flags to grow up verbose level.
