### ISSUE TITLE
Problem with copying generated columns

### ISSUE THREAD

**Issue by ruslan-kurbanov-jr** [datanymizer/datanymizer#189]
Anonymizer throws error when dealing with table with generated columns

Error: db error: ERROR: column "tsv" is a generated column
DETAIL: Generated columns cannot be used in COPY.

pg_dump on its own works fine.

postgresql and pg_dump version is 12.12
pg_datanymizer version is 0.6.0

**Comment by akirill0v** [comment]
@ruslan-kurbanov-jr Thanks, It's interesting problem... We'll research it as soon as possible.
The main approach we use is to replace COPY stage in the dump... We'll see how pg_dumper uses it when working with similar columns.

**Comment by BillBuilt** [comment]
i just ran in to this problem as well. Is there a solution?

pg_dump (PostgreSQL) 16.0
pg_datanymizer version is 0.6.0

**Comment by gregwebs** [comment]
A workaround approach for this could be to create a view of the table and dump that instead (using table filters). Do a find and replace on the dump file before importing to rename the view to the table name.

It seems like PG is supposed to work if the dump value for the generated column is `default`: https://stackoverflow.com/questions/64600614/restoring-pg-database-from-dump-fails-due-to-generated-columns

**Comment by BillBuilt** [comment]
Tried adding the `--inserts` pg_dump argument but it still used COPY. I was hoping that since the error specifically mentioned COPY, then using `--inserts` would allow it to work.

**Comment by ruslan-kurbanov-jr** [comment]
Thanks a lot! Is new release going to be published?
