### ISSUE TITLE
In-place data modification

### ISSUE THREAD

**Issue by andrsp** [datanymizer/datanymizer#71]
Hi! Is it possible to make it work to change data in-place (without dump-restore cycle)?
We already have automated backups-to-staging restoration cycle (postgres, basebackups) and would like to use this tool to make data masking in-place.

**Comment by evgeniy-r** [comment]
Hello!

You can redirect the datanymizer output to the input of `psql`. But be careful not to accidentally damage some data.

**Comment by evgeniy-r** [comment]
Does this suit your use case?

**Comment by andrsp** [comment]
Thanks for the advice, but looks like not, actually :(
Obviously I can redirect output and push data back only to different database, not the same which is the source for pg_datanymizer:
this wont work → 
`pg_datanymizer -c config.yaml postgres://test:test@localhost/test | psql postgres://test:test@localhost/test
`
this will work → 
`pg_datanymizer -c config.yaml postgres://test:test@localhost/test | psql postgres://test:test@localhost/test_new
`

**Comment by evgeniy-r** [comment]
Hello again.

Implementation of such a feature will require quite a lot of work, and therefore we will not be able to implement it in the near future. I'm sorry.

You can also dump to a new database, then drop the old one, and then rename the new one.
