### ISSUE TITLE
Possible to exclude owner/privilege information

### ISSUE THREAD

**Issue by mcg** [datanymizer/datanymizer#74]
Using `pg_dump` and `pg_restore` you can exclude owner/priv information using `--no-owner` and `--no-privileges`. Using `psql < dump` to do restores as documented, doesn't allow this type of thing. Is this possible without having to manually text process the dump file?

**Comment by evgeniy-r** [comment]
Hello!

It is not possible for now, but I think we can implement this feature.

**Comment by evgeniy-r** [comment]
An example of the required command (on the `main` branch):
```
pg_datanymizer -c some_config.yml -f some_dump.sql -- postgres://postgres:postgres@localhost/some_db --no-owner --no-privileges
```

**Comment by evgeniy-r** [comment]
https://github.com/datanymizer/datanymizer/blob/main/docs/pg_datanymizer.md#args

**Comment by mcg** [comment]
Thanks for the changes. Running some tests with this now.

**Comment by mcg** [comment]
Seems to be working for us. Thanks!
